[pytest]
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated:DeprecationWarning
